version: '3'

services:
  keycloak:
      image: quay.io/keycloak/keycloak:17.0.1-legacy
      environment:
        ROOT_LOGLEVEL: INFO
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: admin
        DB_VENDOR: h2
      ports:
        - 8080:8080
      volumes:
        - data:/opt/jboss/keycloak/standalone/data
  gocd:
    image: gocd/gocd-server:v22.3.0
    volumes:
      - data:/godata
      - ./plugins:/godata/plugins
    ports:
      - 8153:8153
      - 8154:8154

volumes:
  data: